#!/usr/bin/bash -xe

d:
  sudo npm run dev

f:
  npx prettier --write .

s:
  npx astro sync

b:
  npx astro build

p:
  npx astro preview

cert:
  mkdir -p .cert && mkcert -key-file ./.cert/localhost-key.pem -cert-file ./.cert/localhost.pem 'calendar-telegram-web-app.local'
